name: dapautoparts
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  http: ^0.13.5
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  pdf: ^3.10.1
  printing: ^5.11.0
  path_provider: ^2.1.0
  flutter_email_sender: ^7.0.0
  screenshot: ^2.1.0
  open_file: ^3.3.2  # Para abrir archivos PDF
  permission_handler: ^11.0.0  # Para gestionar permisos

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/imagenesProductos/
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  image_path: "assets/images/LogoParaHome.png"
